import streamlit as st
from ingest import ingest_pdf
from rag_chain import load_qa_chain
import tempfile, os, shutil
from datetime import datetime


st.set_page_config(
    page_title="RAG PDF Chatbot",
    page_icon="📄",
    layout="centered"
)


# ── Format Instructions per Query Type ──────────────────
FORMAT_INSTRUCTIONS = {
    "compare": """
Structure your response as:
**Aspect 1: [name]**
- [Item A]: ...
- [Item B]: ...

**Aspect 2: [name]**
- [Item A]: ...
- [Item B]: ...

End with a **Summary** sentence.
""",
    "summarize": """
Structure your response as:
**Overview:** One sentence summary.

**Key Points:**
- Point 1
- Point 2
- Point 3

**Conclusion:** One closing sentence.
""",
    "definition": """
Structure your response as:
**Definition:** Clear one-sentence definition.

**In context:** How this term is used in the document.

**Example (if available):** A concrete example from the text.
""",
    "explain": """
Structure your response as:
**Explanation:** Start with a plain-language summary.

**How it works:**
1. Step or concept 1
2. Step or concept 2

**Why it matters:** One sentence on significance.
""",
    "general": """
Answer directly and concisely.
Use bullet points only if listing multiple items.
Keep it under 5 sentences unless more detail is needed.
""",
}


# ── Query Intent Filter ──────────────────────────────────
def is_retrieval_needed(query: str) -> bool:
    casual_words = [
        "hi", "hello", "thanks", "thank you",
        "ok", "okay", "bye", "cool", "great"
    ]
    return not any(word in query.lower() for word in casual_words)


# ── Query Classifier ─────────────────────────────────────
def classify_query(query: str) -> str:
    q = query.lower()
    if any(word in q for word in ["difference", "compare", "vs", "versus"]):
        return "compare"
    elif any(word in q for word in ["summarize", "summary"]):
        return "summarize"
    elif any(word in q for word in ["what is", "define", "meaning"]):
        return "definition"
    elif any(word in q for word in ["explain", "how", "why"]):
        return "explain"
    else:
        return "general"


# ── Chat Export Builder ──────────────────────────────────
def build_export_text(messages: list, indexed_files: list) -> str:
    lines = []
    lines.append("=" * 60)
    lines.append("PDF CHAT EXPORT")
    lines.append(f"Exported: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    lines.append(f"Documents: {', '.join(indexed_files) if indexed_files else 'None'}")
    lines.append("=" * 60)
    lines.append("")

    for msg in messages:
        role = "You" if msg["role"] == "user" else "Assistant"
        lines.append(f"[{role}]")
        lines.append(msg["content"])
        lines.append("")

    lines.append("=" * 60)
    lines.append("Generated by PDF RAG Chatbot")
    return "\n".join(lines)


# ── Page Header ──────────────────────────────────────────
st.title("📄 RAG PDF Chatbot")
st.caption("Upload PDFs and ask anything — powered by RAG + Groq")

mode_toggle = st.toggle("Smart Mode", value=True)
mode = "smart" if mode_toggle else "strict"
st.caption(
    "Smart Mode: Uses AI + documents  |  "
    "Strict Mode: Only answers from uploaded PDFs"
)


# ── Sidebar ──────────────────────────────────────────────
with st.sidebar:
    st.header("Upload your documents")

    uploaded_files = st.file_uploader(
        "Choose one or more PDFs",
        type="pdf",
        accept_multiple_files=True
    )

    if uploaded_files:
        new_files = [
            f.name for f in uploaded_files
            if f.name not in st.session_state.get("indexed_files", [])
        ]

        if new_files:
            with st.spinner(f"Indexing {len(new_files)} file(s)..."):
                for f in uploaded_files:
                    if f.name in new_files:
                        with tempfile.NamedTemporaryFile(delete=False, suffix=".pdf") as tmp:
                            tmp.write(f.read())
                            tmp_path = tmp.name
                        ingest_pdf(tmp_path)
                        os.unlink(tmp_path)

            st.session_state.setdefault("indexed_files", [])
            st.session_state["indexed_files"].extend(new_files)
            st.session_state["indexed"] = True
            st.success(f"{len(new_files)} new file(s) indexed.")

    if st.session_state.get("indexed_files"):
        st.success(f"{len(st.session_state['indexed_files'])} file(s) ready")
        st.markdown("**Indexed files:**")
        for name in st.session_state["indexed_files"]:
            st.markdown(f"- {name}")

    st.divider()

    if st.session_state.get("messages"):
        export_text = build_export_text(
            st.session_state.messages,
            st.session_state.get("indexed_files", [])
        )
        st.download_button(
            label="Export chat (.txt)",
            data=export_text,
            file_name=f"chat_export_{datetime.now().strftime('%Y%m%d_%H%M%S')}.txt",
            mime="text/plain",
            use_container_width=True
        )
    else:
        st.button(
            "Export chat (.txt)",
            disabled=True,
            use_container_width=True,
            help="Start a conversation first to enable export"
        )

    st.divider()

    if st.button("Clear chat & reset", use_container_width=True):
        st.session_state.clear()
        st.rerun()


# ── Chat History Display ─────────────────────────────────
if "messages" not in st.session_state:
    st.session_state.messages = []

for msg in st.session_state.messages:
    with st.chat_message(msg["role"]):
        st.markdown(msg["content"])


# ── Chat Input ───────────────────────────────────────────
if question := st.chat_input("Ask something about your PDFs..."):

    if not st.session_state.get("indexed"):
        st.warning("Please upload at least one PDF first.")

    else:
        st.session_state.messages.append({"role": "user", "content": question})
        with st.chat_message("user"):
            st.markdown(question)

        with st.chat_message("assistant"):

            query_type = classify_query(question)
            format_instructions = FORMAT_INSTRUCTIONS.get(
                query_type, FORMAT_INSTRUCTIONS["general"]
            )

            st.caption(f"Query type: {query_type.capitalize()}")

            chain, retriever, history = load_qa_chain(
                st.session_state.messages,
                mode=mode
            )

            response_container = st.empty()
            full_text = ""

            with st.spinner("Thinking..."):
                for chunk in chain.stream({
                    "input": question,
                    "chat_history": history,
                    "query_type": query_type,
                    "format_instructions": format_instructions,
                }):
                    if "answer" in chunk:
                        full_text += chunk["answer"]
                        response_container.markdown(full_text + "▌")

            response_container.markdown(full_text)

            # ── Sources ───────────────────────────────────
            if is_retrieval_needed(question):
                sources = retriever.invoke(question)

                if sources:
                    with st.expander("View Sources"):
                        file_groups: dict = {}
                        for doc in sources:
                            raw_source = doc.metadata.get("source", "Unknown file")
                            file_name = os.path.basename(raw_source)
                            page = doc.metadata.get("page", None)
                            page_num = page + 1 if page is not None else "?"
                            snippet = doc.page_content[:200].strip().replace("\n", " ")

                            if file_name not in file_groups:
                                file_groups[file_name] = []
                            file_groups[file_name].append((page_num, snippet))

                        for file_name, entries in file_groups.items():
                            st.markdown(f"**{file_name}**")
                            for page_num, snippet in entries:
                                st.markdown(f"> Page {page_num}: {snippet}...")
                            st.divider()

        st.session_state.messages.append({"role": "assistant", "content": full_text})
